<MyLayout>
    do_default_tab: False

    TabbedPanelItem:
        text: "Tab 1"
        Label:
            text: "hello World"

    TabbedPanelItem:
        text: "Tab 2"
        BoxLayout:
            Label:
                text: "Press The Button =>"
            Button:
                text: "Click Me!"


    TabbedPanelItem:
        text: "Tab 3"

        Image:
            source: "../images/jungle.jpg"







