<MyLayout>
    do_default_tab: False

    size_hint: 1, 1
    pos_hint: { 'center_x': .5, 'center_y': .5 }

    #tab_pos: 'bottom_mid'
    #tab_pos: 'top_mid'
    #tab_pos: 'right_top'
    #tab_pos: 'right_mid'
    tab_pos: 'left_mid'

    TabbedPanelItem:
        text: "Tab 1"
        Label:
            text: "hello World"

    TabbedPanelItem:
        text: "Tab 2"
        BoxLayout:
            Label:
                text: "Press The Button =>"
            Button:
                text: "Click Me!"


    TabbedPanelItem:
        text: "Tab 3"

        Image:
            source: "../images/jungle.jpg"

    TabbedPanelItem:
        text: "Tab 4"

        Image:
            source: "../images/jungle-canopy-image.webp"







