<MyLayout>

    BoxLayout:
        #orientation: "horizontal"
        orientation: "vertical"
        size: root.width, root.height

        Accordion:
            orientation: "vertical"
            #orientation: "horizontal"

            AccordionItem:
                title: "Panel 1"
                Image:
                    source: "images/image_1.jpg"


            AccordionItem:
                title: "Panel 2"
                Image:
                    source: "images/image_2.jpg"
            AccordionItem:
                title: "Panel 3"
                Image:
                    source: "images/image_3.jpg"

            AccordionItem:
                title: "Panel 4"
                Image:
                    source: "images/image_1.jpg"










