<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        Label:
            markup: True
            font_size: 32
            text: "This is  [color=#FF4500][b]Bold[/b][/color] [font=times]text[/font] [sup]Up[/sup] and [sub]Down[/sub]"

        Label:
            markup: True
            font_size: 32
            text: "This is [size=80][i]Italics[/i][/size] [font=times]text[/font]"

        Button:
            markup: True
            font_size: 32
            text: "[size=50][u]Click[/u][/size] [font=times][s][i]ME[/i][/s][/font]!"
















