<MyLayout>
    BoxLayout:
        #orientation: "horizontal"
        orientation: "vertical"
        size: root.width, root.height

        padding: 50
        spacing: 20

        Button:
            text: "Hello"

        Button:
            text: "Goodbye"

        Button:
            text: "I'm Hungry "
            pos_hint: {'center_x': 0.5}
            size_hint: (1, 0.2)
            #----------------
            #size_hint: (None, None)
            #width: 200
            #height: 50


