#:import utils kivy.utils
<MyGridLayout>

    name: name
    pizza: pizza
    color: color

    GridLayout:
        cols:1
        size: root.width, root.height

        GridLayout:
            cols:2

            Label:
                text: "Name"
            TextInput:
                id: name
                multiline: False
                background_normal: ''
                background_color: utils.get_color_from_hex('#3B1509')

            Label:
                text: "Favorite Pizza"
            TextInput:
                id: pizza
                multiline: False
                background_normal: ''
                background_color: utils.get_color_from_hex('#3B2209')

            Label:
                text: "Favorite Color"
            TextInput:
                id: color
                multiline: False
                background_normal: ''
                background_color: utils.get_color_from_hex('#3B1509')
        Button:
            text: "Submit"
            font_size: 32
            on_press: root.press()
            #RGB - A
            background_normal: ''
            #background_color: (59/255,34/255,9/255,1)

            background_color: utils.get_color_from_hex('#3B2209')
