Screen:

    #MDRaisedButton:
    #    text: "First button"
    #    pos_hint: {"center_x": .5, "center_y": .8}
#---------------------------------------------------------------
    MDButton:
        style: "filled"
        pos_hint: {"center_x": .5, "center_y": .8}

        MDButtonText:
            text: "First button"

#---------------------------------------------------------------
    MDButton:
        style: "filled"
        pos_hint: {"center_x": .5, "center_y": .6}

        MDButtonText:
            text: "Second button"