<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        Screen:

            BoxLayout:
                orientation: "vertical"
                spacing: "10dp"
                size_hint: None, None
                size: "280dp", "230dp"
                pos_hint: {"center_x": .5, "center_y": .5}

                MDCard:
                    orientation: "vertical"
                    padding: "8dp"
                    size_hint: None, None
                    size: "280dp", "180dp"

                    MDLabel:
                        text: "Title"
                        theme_text_color: "Secondary"
                        size_hint_y: None
                        height: self.texture_size[1]

                    MDDivider:
                        height: "1dp"

                    MDLabel:
                        text: "Body"

                MDSlider:
                    min: 0
                    max: 100
                    value: 40