<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        padding: 50
        spacing: 20

        Label:
            id: my_label
            text: "Hello world"
            font_size: 32

        Button:
            text: "Hello"
            font_size: 32
            size_hint: .18, .18
            background_color: 0,0,0,0


            Image:
                source: "../images/jungle-canopy-image.webp"
                center_x: self.parent.center_x
                center_y: self.parent.center_y










