<MyLayout>

    BoxLayout:
        #orientation: "horizontal"
        orientation: "vertical"
        size: root.width, root.height

        Carousel:
            direction: "right"
            #direction: "top"
            loop: True

            Image:
                source: "images/image_1.jpg"

            AsyncImage:
                source: 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Fronalpstock_big.jpg'

            Image:
                source: "images/image_2.jpg"

            Image:
                source: "images/image_3.jpg"

            AsyncImage:
                source: 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Fronalpstock_big.jpg'






