<MyLayout>

    BoxLayout:
        #orientation: "horizontal"
        orientation: "vertical"
        size: root.width, root.height

        TextInput:
            id: calc_input
            text: "0"
            halign: "right"
            font_size: 65
            size_hint: (1, .15)

        GridLayout:
            cols: 4
            rows: 5

            #Row 1
            Button:
                id: id_%
                size_hint: (.2,.2)
                font_size: 32
                text: "%"

            Button:
                id: id_CE
                size_hint: (.2,.2)
                font_size: 32
                text: "CE"

            Button:
                id: id_clear
                size_hint: (.2,.2)
                font_size: 32
                text: "C"
                on_press: root.clear()

            Button:
                id: id_slash
                size_hint: (.2,.2)
                font_size: 32
                text: "/"
#-------------------------------------------------------
#Row 2
            Button:
                id: id_7
                size_hint: (.2,.2)
                font_size: 32
                text: "7"
                background_color: (157/255,157/255,157/255,1)

            Button:
                id: id_8
                size_hint: (.2,.2)
                font_size: 32
                text: "8"
                background_color: (157/255,157/255,157/255,1)

            Button:
                id: id_9
                size_hint: (.2,.2)
                font_size: 32
                text: "9"
                background_color: (157/255,157/255,157/255,1)

            Button:
                id: id_x
                size_hint: (.2,.2)
                font_size: 32
                text: "X"

#--------------------------------------------------------------
#Row 3
            Button:
                id: id_4
                size_hint: (.2,.2)
                font_size: 32
                text: "4"
                background_color: (157/255,157/255,157/255,1)

            Button:
                id: id_5
                size_hint: (.2,.2)
                font_size: 32
                text: "5"
                background_color: (157/255,157/255,157/255,1)

            Button:
                id: id_6
                size_hint: (.2,.2)
                font_size: 32
                text: "6"
                background_color: (157/255,157/255,157/255,1)

            Button:
                id: id_minus
                size_hint: (.2,.2)
                font_size: 32
                text: "-"

#----------------------------------------------------------
#Row 4
            Button:
                id: id_1
                size_hint: (.2,.2)
                font_size: 32
                text: "1"
                background_color: (157/255,157/255,157/255,1)

            Button:
                id: id_2
                size_hint: (.2,.2)
                font_size: 32
                text: "2"
                background_color: (157/255,157/255,157/255,1)

            Button:
                id: id_3
                size_hint: (.2,.2)
                font_size: 32
                text: "3"
                background_color: (157/255,157/255,157/255,1)

            Button:
                id: id_plus
                size_hint: (.2,.2)
                font_size: 32
                text: "+"

#------------------------------------------------------------
#Row 5
            Button:
                id: id_n1
                size_hint: (.2,.2)
                font_size: 32
                text: "+/-"

            Button:
                id: id_n2
                size_hint: (.2,.2)
                font_size: 32
                text: "0"
                background_color: (157/255,157/255,157/255,1)

            Button:
                id: id_n3
                size_hint: (.2,.2)
                font_size: 32
                text: "."

            Button:
                id: id_n4
                size_hint: (.2,.2)
                font_size: 32
                text: "="






