<MyLayout>

    BoxLayout:
        #orientation: "horizontal"
        orientation: "vertical"
        size: root.width, root.height

        #padding: 50
        #spacing: 20

        Image:
            #source: 'images/jungle.jpg'
            source: 'images/jungle-canopy-image.webp'
            allow_stretch: True
            #Співвідношення сторін самого зображення
            keep_ratio: False

        #Button:
            #text: "Hello"








